# Generated by Django 3.0.2 on 2020-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(max_length=10)),
                ('website', models.CharField(max_length=20)),
            ],
        ),
    ]
